fix: add 'With' methods to HttpServerConfiguration
gravitee-io/gravitee-node pull request #201
Opened 2023-03-30 14:13 UTC by ytvnr

**Issue**

https://gravitee.atlassian.net/browse/APIM-1381

**Description**

HttpServerConfiguration builder implementation was only relying on Environment so set default values.
Add lombok's `@With` to be able to set fields after builds with an immutable object.

---
**Gravitee.io Automatic Deployment**

🚀 A prerelease version of this package has been published on Gravitee's private artifactory, you can:
 - use it directly by updating your project with version: `1.24.6-apim-1381-debugmode-secured-3-18-SNAPSHOT`
 - download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/node/gravitee-node/1.24.6-apim-1381-debugmode-secured-3-18-SNAPSHOT/gravitee-node-1.24.6-apim-1381-debugmode-secured-3-18-SNAPSHOT.zip)

2023-03-30 14:56 UTC, jhaeyaert requested changes

2023-03-30 14:56 UTC, jhaeyaert commented on pom.xml
> +            <version>${lombok.version}</version>
Unless I'm missing something, you forgot the `provided` scope no?

2023-03-31 08:37 UTC, phiz71 approved these changes

2023-03-31 08:38 UTC, merged

2023-03-31 08:41 UTC, graviteeio commented
:tada: This PR is included in version 1.24.6 :tada:

The release is available on:
- `1.24.6`
- [GitHub release](https://github.com/gravitee-io/gravitee-node/releases/tag/1.24.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-04-27 12:46 UTC, graviteeio commented
:tada: This PR is included in version 2.0.7 :tada:

The release is available on:
- `2.0.7`
- [GitHub release](https://github.com/gravitee-io/gravitee-node/releases/tag/2.0.7)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-04-27 13:16 UTC, graviteeio commented
:tada: This PR is included in version 3.0.6 :tada:

The release is available on:
- `3.0.6`
- [GitHub release](https://github.com/gravitee-io/gravitee-node/releases/tag/3.0.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: