feat: add OpenTelemetry feature into Gravitee Node
gravitee-io/gravitee-node pull request #374
Opened 2024-10-11 15:29 UTC by guillaumelamirand

**Issue**

https://gravitee.atlassian.net/browse/ARCHI-401

**Description**

The objective is to provide a generic way for Gravitee Application to manage tracing based on OpenTelemetry specification.

**Additional context**

2024-10-30 15:55 UTC, jhaeyaert requested changes

2024-11-05 10:59 UTC, guillaumelamirand commented on gravitee-node-opentelemetry/src/main/java/io/gravitee/node/opentelemetry/OpenTelemetryFactory.java
> +                .addSpanProcessor(BatchSpanProcessor.builder(exporterFactory.createSpanExporter()).build())
See https://gravitee.atlassian.net/browse/ARCHI-428

2024-11-05 10:59 UTC, guillaumelamirand commented on gravitee-node-opentelemetry/src/main/java/io/gravitee/node/opentelemetry/exporter/ExporterFactory.java
> +        return new VertxGrpcSpanExporter(
See https://gravitee.atlassian.net/browse/ARCHI-427

2024-11-05 12:29 UTC, jhaeyaert approved these changes

2024-11-05 13:30 UTC, merged

2024-11-05 13:38 UTC, graviteeio commented
:tada: This PR is included in version 7.0.0-alpha.1 :tada:

The release is available on:
- `7.0.0-alpha.1`
- [GitHub release](https://github.com/gravitee-io/gravitee-node/releases/tag/7.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-12-30 10:25 UTC, graviteeio commented
:tada: This PR is included in version 7.0.0 :tada:

The release is available on:
- `7.0.0`
- [GitHub release](https://github.com/gravitee-io/gravitee-node/releases/tag/7.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: