fix(event): propagate node stop event when shutdown
gravitee-io/gravitee-node pull request #73
Opened 2021-09-02 15:16 UTC by jhaeyaert

Closes gravitee-io/issues#5966

2021-09-11 08:09 UTC, brasseld requested changes

2021-09-11 08:09 UTC, brasseld commented on gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/monitor/NodeMonitorService.java
> +        LOGGER.info("Gateway monitor already shut-downed");
Gateway monitor -> Node monitor

2021-09-13 08:47 UTC, jhaeyaert commented on gravitee-node-monitoring/src/main/java/io/gravitee/node/monitoring/monitor/NodeMonitorService.java
> +        LOGGER.info("Gateway monitor already shut-downed");
Good catch!

2021-09-16 08:34 UTC, phiz71 approved these changes

2021-09-16 08:34 UTC, merged